#!/usr/bin/env python3
"""
Combine all Python files in the repository `lib/` folder into a single
overview text file at `scripts/combined_lib_overview.txt`.

This script writes a plain text file (not executable Python) where each
section begins with a clear marker indicating the original filename.
"""

import os
import glob


def main():
    repo_root = os.path.dirname(os.path.dirname(__file__))
    lib_dir = os.path.join(repo_root, "lib")
    out_path = os.path.join(os.path.dirname(__file__), "combined_lib_overview.txt")

    py_files = sorted(glob.glob(os.path.join(lib_dir, "*.py")))

    with open(out_path, "w", encoding="utf-8") as out:
        out.write("Combined overview of lib/*.py\n")
        out.write("Generated by scripts/combine_lib_files.py\n\n")

        for fp in py_files:
            rel = os.path.relpath(fp, repo_root)
            out.write("----- FILE: {} -----\n\n".format(rel))
            with open(fp, "r", encoding="utf-8") as f:
                out.write(f.read())
            out.write("\n\n")

    print("Wrote:", out_path)


if __name__ == "__main__":
    main()
