#!/usr/bin/env python3
"""
Combine all Python files in the repository `lib/` folder into a single
overview text file at `scripts/combined_lib_overview.txt`.

This script writes a plain text file (not executable Python) where each
section begins with a clear marker indicating the original filename.
"""

import os
import glob
import subprocess


def main():
    repo_root = os.path.dirname(os.path.dirname(__file__))
    lib_dir = os.path.join(repo_root, "lib")
    out_path = os.path.join(os.path.dirname(__file__), "combined_lib_overview.txt")

    # Files to ignore (repository-relative paths). Add more entries here as needed.
    # Example: "lib/probabilities.py"
    IGNORE_FILES = {
        "lib/probabilities.py",
        "lib/__init__.py",
        "lib/equilibrium/__init__.py",
        "lib/equilibrium/excel_styling.py",
        "lib/equilibrium/excel_writer.py",
        "lib/equilibrium/scenarios.py",
        "lib/errors.py",
        "lib/logging.py",
        
    }

    # Collect Python files recursively under lib/, excluding __pycache__ directories.
    py_pattern = os.path.join(lib_dir, "**", "*.py")
    py_files = sorted(glob.glob(py_pattern, recursive=True))
    py_files = [fp for fp in py_files if "__pycache__" not in fp.split(os.sep)]

    # Normalize and filter repository-relative ignore paths
    ignore_rel = {os.path.normpath(p) for p in IGNORE_FILES}
    def is_ignored(fp):
        rel = os.path.relpath(fp, repo_root)
        return os.path.normpath(rel) in ignore_rel

    py_files = [fp for fp in py_files if not is_ignored(fp)]

    with open(out_path, "w", encoding="utf-8") as out:
        out.write("Combined overview of lib/**/*.py\n")
        out.write("Generated by scripts/combine_files.py\n\n")
        
        # Add tree output at the top
        out.write("----- REPOSITORY TREE -----\n\n")
        try:
            # Exclude the `viz` directory from the repository tree output
            result = subprocess.run(
                ["tree", "-I", "viz", repo_root],
                capture_output=True,
                text=True,
                check=True
            )
            out.write(result.stdout)
        except subprocess.CalledProcessError as e:
            out.write(f"Error running tree command: {e}\n")
        except FileNotFoundError:
            out.write("tree command not found. Please install it.\n")
        out.write("\n\n")

        for fp in py_files:
            rel = os.path.relpath(fp, repo_root)
            out.write("----- FILE: {} -----\n\n".format(rel))
            with open(fp, "r", encoding="utf-8") as f:
                out.write(f.read())
            out.write("\n\n")

    # Now create a separate overview for TypeScript files under viz/
    viz_out_path = os.path.join(os.path.dirname(__file__), "combined_viz_overview.txt")
    viz_dir = os.path.join(repo_root, "viz")
    with open(viz_out_path, "w", encoding="utf-8") as vout:
        vout.write("Combined overview of viz/**/*.ts\n")
        vout.write("Generated by scripts/combine_lib_files.py\n\n")

        vout.write("----- VIZ TREE (excluding node_modules) -----\n\n")
        if os.path.isdir(viz_dir):
            try:
                # Use tree excluding node_modules for readability
                result = subprocess.run(
                    ["tree", "-I", "node_modules", viz_dir],
                    capture_output=True,
                    text=True,
                    check=True,
                )
                vout.write(result.stdout)
            except subprocess.CalledProcessError as e:
                vout.write(f"Error running tree command on viz/: {e}\n")
            except FileNotFoundError:
                vout.write("tree command not found. Please install it.\n")
            vout.write("\n\n")

            ts_pattern = os.path.join(viz_dir, "**", "*.ts")
            ts_files = sorted(glob.glob(ts_pattern, recursive=True))
            # Exclude any files in node_modules
            ts_files = [fp for fp in ts_files if "node_modules" not in fp.split(os.sep)]

            if ts_files:
                for fp in ts_files:
                    rel = os.path.relpath(fp, repo_root)
                    vout.write("----- FILE: {} -----\n\n".format(rel))
                    with open(fp, "r", encoding="utf-8") as f:
                        vout.write(f.read())
                    vout.write("\n\n")
            else:
                vout.write("No .ts files found under viz/ (excluding node_modules)\n\n")
        else:
            vout.write(f"No viz directory found at {viz_dir}\n\n")
    print("Wrote:", out_path)
    print("Wrote:", viz_out_path)


if __name__ == "__main__":
    main()
